name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build_profile_achievements:
    if: 'github.event_name == ''push'' && contains(github.event.commits[*].added, ''profile_achievements/'') || contains(github.event.commits[*].modified, ''profile_achievements/'')'
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Docker image for profile_achievements
        run: |
          cd profile_achievements
          docker build -t pogr_interview_test:profile_achievements .

  build_game_profiles:
    if: 'github.event_name == ''push'' && contains(github.event.commits[*].added, ''game_profiles/'') || contains(github.event.commits[*].modified, ''game_profiles/'')'
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Docker image for game_profiles
        run: |
          cd game_profiles
          docker build -t pogr_interview_test:game_profiles .
  build_profile_overview:
    if: 'github.event_name == ''push'' && contains(github.event.commits[*].added, ''profile_overview/'') || contains(github.event.commits[*].modified, ''profile_overview/'')'
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Docker image for profile_overview
        run: |
          cd profile_overview
          docker build -t pogr_interview_test:profile_overview .
