name: Game Profile Build

on:
  push:
    branches:
      - main
    paths:
      - "game_profile/**"
      - ".github/workflows/game_profile.yml"
jobs:
  build_game_profile:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x

      - name: Build Docker image for game_profile
        run: |
          cd game_profile
          docker build -t pogr_interview_test:game_profile:$GITHUB_RUN_NUMBER .
