name: Game Profile Build

on:
  push:
    branches:
      - main
    paths:
      - "game_profiles/**"
      - ".github/workflows/game_profiles.yml"
jobs:
  build_game_profiles:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x

      - name: Build Docker image for game_profiles
        run: |
          cd game_profiles
          docker build -t pogr_interview_test:game_profiles:$GITHUB_RUN_NUMBER .
